    version: '3.5'
    
    services:
      postgres:
        image: postgres:latest
        environment:
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
        volumes:
          - postgres:/data/postgres
        ports:
          - "5432:5432"
        networks:
          - postgres
        restart: unless-stopped
        command: bash -c 'if [ ! -d "$PGDATA" ]; then gosu postgres initdb; gosu postgres pg_ctl -D "$PGDATA" -o "-c listen_addresses='' -c max_connections=100" -w start; gosu postgres psql -U postgres -d postgres -c "CREATE DATABASE mydatabase"; gosu postgres pg_ctl -D "$PGDATA" -w stop; fi; gosu postgres postgres'
      pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
        ports:
          - "8081:80"
        depends_on:
          - postgres
        networks:
          - postgres
    
    networks:
      postgres:
        driver: bridge
    
    volumes:
        postgres:
